
server:
  port: 7000
spring:
  application:
    name: product-service
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///taobap_product?useUnicode=true&characterEncoding=utf8
    username: root
    password: root